### PR TITLE
add params to bootstrap constructor

### PR DESCRIPTION
**Pull request by maciejmrozinski**
$appenv and $debug params should be passed to bootstrap constructor

### CODE REVIEW

**Comment by franzliedke** [comment]
Hmm, is that some kind of global convention?
I guess it's not really a problem as PHP does not fail if you pass more arguments to a method than it has declared.

However, I think I'd prefer an optional interface as part of this package. Something like this:

``` php
interface PpmMiddleware {
    public function initializePPM($appEnv, $debug);
}
```

Then, if the middleware implements that interface, we use this method to pass the additional data to it.
What do you think?

**Comment by maciejmrozinski** [comment]
My track was that all PPM bootstraps should implement this interface:
https://github.com/php-pm/php-pm/blob/master/Bootstraps/BootstrapInterface.php

In this interface __construct has a 2 arguments. Right now these params get lost.

**Comment by franzliedke** [comment]
Ah, thanks for bringing that up!

I don't really think it's a good idea to include a constructor in an interface like that, as that makes dependency injection unnecessarily hard (and really, interfaces don't have much use for class methods, IMO).

Could that be changed, @marcj ?

**Comment by marcj** [comment]
I actually like that __construct in the interface as it gives instantly the information that you get `appenv` and `$debug` as arguments. There's no other place where this informations is coming from.

**Comment by maciejmrozinski** [comment]
Any final decision here? :)

**Comment by maciejmrozinski** [comment]
bump? @franzliedke @marcj

**Comment by franzliedke** [comment]
Hmm, I'm open to doing this if you think that it has to be done.

I still consider having the constructor as part of the interface a bad idea. Quoting from [here](https://www.quora.com/Why-are-constructors-not-inherited):

> More importantly, the main benefit of inheritance do not apply to constructors:
> The main benefit of inheritance is subtype polymorphism. If you have a pointer or a reference to a base class type, it can point to an object of that type or any derived type. You can access fields and virtual methods using that pointer/reference to base class type, and it will work even if the pointer points to an object of derived class type, without you knowing, or caring, what that type actually is. However, for constructors, this is not relevant, because any place where a constructor is invoked, you explicitly specify the class name to be constructed. There is no situation where you could call a constructor on an object that could possibly be different types; it wouldn't make sense.

But that would require changes in PHPPM's core. What do you think, @marcj ?

**Comment by maciejmrozinski** [comment]
I must agree with @franzliedke about constructors in interfaces. In last few days doing other things i faced 2-3 articles clearly stated that __constructs shouldn't be included in interfaces. So i think it's better to rethink how we should do this.

**Comment by marcj** [comment]
>  There is no situation where you could call a constructor on an object that could possibly be different types; it wouldn't make sense.

Not exactly true in the PHP world. I guess this text is for a different language, isn't it?

However, I'm open to swap this out to an additional interface.

**Comment by franzliedke** [comment]
IMO, interfaces are only useful when PHP can enforce them - which it can only do for objects, not class names (strings). To use a constructor, you can't use an object that implements the interface, but need the class name, which should refer to a class that implements that interface.

If anything, this kind of interface is only useful in a factory context, which I guess is partially true here. I wonder whether it should be possible to pass an instantiated bootstrap object into the bridge class instead, to allow dependency injection / setup for the custom bootstrap class I might use.

**Pull request closed without merging**
