### PR TITLE
WIP: PSR7 compatibility

### PR DESCRIPTION
**Pull request by maciejmrozinski**
- [X] removed Diactoros stuff
- [X] Middleware must implement DelegateInterface
- [X] Update to use ServerRequestInterface instead RequestInterface
- [x] BridgeInterface extends DelegateInterface
- [x] Update docs
- [ ] Clean up `composer.json`, remove `repositories` entries

### CODE REVIEW

**Comment by maciejmrozinski** [comment]
In line with https://github.com/php-pm/php-pm/pull/226

**Comment by franzliedke** [comment]
@maciejmrozinski That's great, thank you!

As you mentioned in https://github.com/php-pm/php-pm/pull/226, this should probably use the `ServerRequestInterface` as well, instead of just the `RequestInterface`, right?

**Comment by maciejmrozinski** [comment]
Yup, waiting for `react/http` with this :)

**Comment by maciejmrozinski** [comment]
@franzliedke usage of `ServerRequestInterface` has landed :)

**Comment by andig** [comment]
@franzliedke and @maciejmrozinski 
Suggesting to close in favour of https://github.com/php-pm/php-pm-psr7/pull/12

**Comment by franzliedke** [comment]
Thanks! We can close this once the other one is ready to merge.

**Comment by andig** [comment]
Superseded by https://github.com/php-pm/php-pm/pull/278 (which still needs more thinking)- this one can be closed?

**Comment by franzliedke** [comment]
Cheers. We should mark this repository as obsolete once php-pm is ready...

**Pull request closed without merging**
